### ISSUE TITLE
Error: "Not a Magento 2 extension file"

### ISSUE THREAD

**Issue by dambrogia** [viperet/vscode-magento-wizard#1]
I am receiving this error when using the command: `MagentoWizard: Inject Dependency`

Our magento convention keeps our code out of app/code like in your example. We use composer to manage everything so inside a custom folder, our code is linked to `vendor/$vendor/$package` by using the `"symlink": true` option within composer.json.

I can image not supporting a custom folder, but developing out of vendor locally is a feature that is supported by composer and it would be great to see it supported here. If it is possible to work out of a custom folder (by search for the magento root directory, reading the namespace or something similar) that would be awesome as well. 

For what it's worth i'm creating a file in `Vendor\Module\Setup\InstallData` inside `vendor/$vendor\$module\Setup\InstallData.php` and receiving this error.

**Comment by viperet** [comment]
At this moment MagentoWizard only supports extensions in /app/code, but I will add support for extensions in /vendor soon. It's just a little more complicated to get namespace and extension name - need to parse composer.json.

**Comment by viperet** [comment]
@dambrogia support for extensions in /vendor was added in v1.1.4
