### ISSUE TITLE
Not able to install extension.

### ISSUE THREAD

**Issue by vinod27agarwal** [viperet/vscode-magento-wizard#11]
I am using VS code version - 1.31.0 that is latest I believe. I tried to install this extension but I am getting error as Unable to install extension '{{extension_name}}' compatible with current version '1.31.0' of VS code is not found
![image](https://user-images.githubusercontent.com/45603726/84139431-776cd600-aa6d-11ea-81a1-28c7803b6be5.png)

**Comment by viperet** [comment]
Thanks for the report, will look into this as quickly as possible

**Comment by viperet** [comment]
@vinod27agarwal your VSCode version is too old, MagentoWizard requires VSCode 1.40.0 or later.
