### ISSUE TITLE
when create new model

### ISSUE THREAD

**Issue by HRashedy** [viperet/vscode-magento-wizard#13]
when create new extension after enter vendor and extension name 
Error come : Error creating extension folder

**Comment by mohdali27** [comment]
Any update ?

**Comment by viperet** [comment]
@mohdali27 @HRashedy please make sure you updated MagentoWizard to 2.4.2 and try to create a new extension. See error details in Output tab, post them here.
![Extension Development Host  - default xml — test (Workspace) 2020-11-15 23-37-23](https://user-images.githubusercontent.com/725651/99197708-bfbabd80-279c-11eb-87c8-0ec722b10450.jpg)

**Comment by mohdali27** [comment]
Hi,

Updated magento wizard to 2.4.2 but still the same issue . Please check the attachment.
<img width="958" alt="mwizard" src="https://user-images.githubusercontent.com/10211990/99288997-63ba6c80-2862-11eb-8037-8ca227124eed.png">

**Comment by viperet** [comment]
@mohdali27 @HRashedy this is fixed in v2.4.3
