### ISSUE TITLE
Error when activating extension

### ISSUE THREAD

**Issue by NetStorm84** [viperet/vscode-magento-wizard#17]
With the latest Master branch I am getting the below erorr when I run the extension in Debug mode. Does anyone have any idea what is causing this error?

`Activating extension 'viperet.vscode-magento-wizard' failed: Invalid Version: .`

**Comment by NetStorm84** [comment]
@viperet Any ideas on this one?

**Comment by viperet** [comment]
@NetStorm84 can you provide more details? Your VSCode, Node.JS version, maybe everything in VSCode 'About' window?

**Comment by NetStorm84** [comment]
Sure... Pasted below.

Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:26:09.944Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-7642-generic

**Comment by viperet** [comment]
@NetStorm84 just an update on this issue: at least am able to reproduce it. Got the same error while trying to build MagentoWizard on Windows.

**Comment by NetStorm84** [comment]
> @NetStorm84 just an update on this issue: at least am able to reproduce it. Got the same error while trying to build MagentoWizard on Windows.

Ah that's good to know!

**Comment by viperet** [comment]
@NetStorm84 this should be fixed in v2.4.3
