### ISSUE TITLE
New files is not using template data

### ISSUE THREAD

**Issue by shundevadt** [viperet/vscode-magento-wizard#28]
When i create a new file in app/code/Vendor/Module/Block/file.php the file is not populated with template data. 
No errors , no template.

**Comment by viperet** [comment]
@shundevadt can you open 'Output' tab, switch to 'MagentoWizard' channel and post log info that from it here (after you try to create a block, or invoke some MagentoWizard command from F1 menu). It should looks like:

```
PHP 7.0.33 (cli) (built: Aug 14 2019 16:33:54) ( NTS )
Found Magento root at /Users/viperet/Documents/Work/Magento
 - Modules: 151
 - Themes: 11
 - Blocks: 3344
Running '/Applications/MAMP/bin/php/php7.0.33/bin/php bin/magento --no-ansi' in /Users/viperet/Documents/Work/Magento
```

**Comment by shundevadt** [comment]
undefined
Looks like we don't have PHP executable available at 'php'. Please set correct path in the extension settings.
Many features would be unavailable without access to PHP executable.

Looks like i depends on php in the client - i will fix it :)
