### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by chedaroo** [viperet/vscode-magento-wizard#3]
Firstly thanks for you work on this and sharing.

I've had a quick play round and the generation features are a big set up from my current collection of snippets.

Are you open to contributions?

**Comment by viperet** [comment]
Yes, sure - this project is open for all kinds of contributions - new templates, new ideas, bug reports, new features, etc.

**Comment by viperet** [comment]
Added 'Contribution' section to the README, closing this issue.
