### ISSUE TITLE
Add ability to configure custom directory for Magento root 

### ISSUE THREAD

**Issue by chedaroo** [viperet/vscode-magento-wizard#4]
Currently, it is assumed that:

- Magento will be installed in the project root
- that all module development will occur within `./app/code/`.

Whilst this is a reasonable assumption, IRL it's not always the case.

Proposal is to:

- [x] Add config for setting path to Magento install dir. (e.g. `./dest/{{ MAGENTO_INSTALLATION }}/`)
- [ ] Add config for setting path to module development dir. (e.g. `./{{ PATH_TO_MAGENTO }}/vendor/`)

@viperet Do you have any opinions on regarding this or implementation before I tackle this?

**Comment by viperet** [comment]
@chedaroo I’m working on a new version that will be more flexible and will support Magento root anywhere in the workspace folder, it would be detected automatically. Will probably add manual override too. Also new version will have better support of the extensions in /vendor/ but I don’t think that create new extension command  should create extensions in /vendor/. I know some devs are working on extensions directly in /vendor/ but is it supported by composer to create new extension manually?

**Comment by viperet** [comment]
@chedaroo btw if you’d like to test new version before it would be released- I can send you vsx when it is ready.

**Comment by viperet** [comment]
@chedaroo you can try new features by installing this packaged extension (vsix) https://github.com/viperet/vscode-magento-wizard/releases/tag/v2.0.0-alpha

**Comment by chedaroo** [comment]
@viperet Nice one, will take a look now

**Comment by viperet** [comment]
@chedaroo support for Magento not in the root of the workspace was added in v2.0.0, root folder would be autodetected, but it is possible to override autodetection in the settings. New modules would be still created under app/code, but if you install some module using composer in vendor/ - all editing features would be supported by MagentoWizard. Even if you module located in the nested dirs (ex. vendor/foo/bar/src/) - as long as it has registration.php and composer.json  - it would be properly recognized and supported.
