### ISSUE TITLE
Possibility of using a remote generated catalog

### ISSUE THREAD

**Issue by manuelcanepa** [viperet/vscode-magento-wizard#5]
Sometimes i need to use a remote generated catalog. I have a PC in which i work, and a server where is installed the Magento store. Will be amazing if the Generate Catalog feature use a catalog already generated.

Maybe another command just to run the "convert catalog" part, so you can generate the catalog manually and then run this command, or you can generate and convert.

**Comment by viperet** [comment]
@manuelcanepa thanks for the feedback! Added option to select the existing XML file to convert when using the 'Generate Catalog' command in v1.3.2
